#CORS
config:
  cors:
    url: ${URL_CORS} #Example: http://localhost:4200, https://myFrontDeployed.newba.com/

#JWT
security:
  jwt:
    tokenName: accessToken
    refreshName: refreshToken
    secretKey: ${SECRET_KEY} #Example Key: a1b2c3d4e5f67890abcdef1234567890abcdef1234567890abcdef12345678 

#Intercalation + Spring Session Redis
spring:
  data:
    redis:
      host: localhost
      port: 6379
  session:
    store-type: redis
  profiles:
    active: ${APP_PROFILE:dev}
  jpa:
    open-in-view: true #In development or debugging
#open-in-view: false #In production
    
#Session server
server:
  servlet:
    session:
      timeout: 20m
      cookie:
        http-only: true