spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: test
    password: 123
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      data-locations: classpath:data.sql