#CORS
config:
  cors:
    url: ${URL_CORS}

#JWT
security:
  jwt:
    tokenName: token
    secretKey: ${SECRET_KEY}

#Intercalation + Spring Session
spring:
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
  profiles:
    active: ${APP_PROFILE:dev}
  jpa:
    open-in-view: false
    
#Session server
server:
  servlet:
    session:
      timeout: 20m
      cookie:
        http-only: true