#CORS
config:
  cors:
    url: ${URL_CORS}

#JWT
security:
  jwt:
    tokenName: token
    secretKey: ${SECRET_KEY}

#Intercalation + Spring Session Redis
spring:
  data:
    redis:
      host: localhost
      port: 6379
  session:
    #store-type: jdbc
    store-type: redis
    #jdbc:
     # initialize-schema: always
  profiles:
    active: ${APP_PROFILE:dev}
  jpa:
    open-in-view: false
    
#Session server
server:
  servlet:
    session:
      timeout: 20m
      cookie:
        http-only: true